import type { CatalogEntry } from '@shared/island'

/**
 * Tudo o que a ilha integra, item a item.
 *
 * Existe como dado, e não só espalhado pelo código, porque é esta lista que a
 * homologação percorre: `tools/island-check.mjs` exercita cada linha contra a
 * máquina e falha se alguma deixar de responder. Uma integração que não está
 * aqui não é considerada entregue.
 *
 * `leitura` observa o sistema; `acao` mexe nele. As duas contam.
 */
export const CATALOG: CatalogEntry[] = [
  // ——— Sistema ———————————————————————————————————————————
  {
    id: 'cpu',
    module: 'sistema',
    kind: 'leitura',
    what: 'Uso do processador',
    source: '/proc/stat (duas amostras)',
  },
  {
    id: 'memoria',
    module: 'sistema',
    kind: 'leitura',
    what: 'Memória em uso e total',
    source: '/proc/meminfo',
  },
  {
    id: 'carga',
    module: 'sistema',
    kind: 'leitura',
    what: 'Carga média do sistema',
    source: '/proc/loadavg',
  },
  {
    id: 'uptime',
    module: 'sistema',
    kind: 'leitura',
    what: 'Há quanto tempo ligado',
    source: '/proc/uptime',
  },
  {
    id: 'processo-topo',
    module: 'sistema',
    kind: 'leitura',
    what: 'Processo que mais consome',
    source: 'ps -eo comm,%cpu',
  },
  {
    id: 'temp-cpu',
    module: 'sistema',
    kind: 'leitura',
    what: 'Temperatura do processador',
    source: 'sensors -j',
  },
  {
    id: 'systemd-falhas',
    module: 'sistema',
    kind: 'leitura',
    what: 'Serviços do systemd com falha',
    source: 'systemctl --failed',
  },
  {
    id: 'portas-escuta',
    module: 'sistema',
    kind: 'leitura',
    what: 'Portas TCP em escuta e o processo dono',
    source: 'ss -ltnp',
  },
  {
    id: 'disco-raiz',
    module: 'sistema',
    kind: 'leitura',
    what: 'Uso do disco raiz',
    source: 'df -B1 /',
  },

  // ——— Placa de vídeo ————————————————————————————————————
  { id: 'gpu-uso', module: 'gpu', kind: 'leitura', what: 'Uso da GPU', source: 'nvidia-smi' },
  {
    id: 'gpu-temp',
    module: 'gpu',
    kind: 'leitura',
    what: 'Temperatura da GPU',
    source: 'nvidia-smi',
  },
  {
    id: 'gpu-memoria',
    module: 'gpu',
    kind: 'leitura',
    what: 'Memória de vídeo em uso',
    source: 'nvidia-smi',
  },

  // ——— Áudio —————————————————————————————————————————
  {
    id: 'volume',
    module: 'audio',
    kind: 'leitura',
    what: 'Volume atual e se está mudo',
    source: 'pactl get-sink-volume/mute',
  },
  {
    id: 'saida-audio',
    module: 'audio',
    kind: 'leitura',
    what: 'Saída de áudio em uso',
    source: 'pactl get-default-sink',
  },
  {
    id: 'audio-vigia',
    module: 'audio',
    kind: 'leitura',
    what: 'Se o HUD de volume está ouvindo o PipeWire',
    source: 'pactl subscribe (island/watch.ts)',
  },
  {
    id: 'mic-mudo',
    module: 'audio',
    kind: 'leitura',
    what: 'Se o microfone está silenciado',
    source: 'pactl get-source-mute',
  },
  {
    id: 'mic-em-uso',
    module: 'audio',
    kind: 'leitura',
    what: 'Quem está gravando do microfone agora',
    source: 'pactl list source-outputs',
  },
  {
    id: 'mic-mudo-alternar',
    module: 'audio',
    kind: 'acao',
    what: 'Silenciar ou liberar o microfone',
    source: 'pactl set-source-mute',
  },
  {
    id: 'audio-definir-saida',
    module: 'audio',
    kind: 'acao',
    what: 'Escolher a saída de áudio pelo nome, movendo os fluxos junto',
    source: 'pactl set-default-sink + move-sink-input',
  },
  {
    id: 'saidas-audio',
    module: 'audio',
    kind: 'leitura',
    what: 'Saídas de áudio disponíveis',
    source: 'pactl -f json list sinks',
  },
  {
    id: 'volume-subir',
    module: 'audio',
    kind: 'acao',
    what: 'Aumentar o volume',
    source: 'pactl set-sink-volume +5%',
  },
  {
    id: 'volume-baixar',
    module: 'audio',
    kind: 'acao',
    what: 'Diminuir o volume',
    source: 'pactl set-sink-volume -5%',
  },
  {
    id: 'volume-mudo',
    module: 'audio',
    kind: 'acao',
    what: 'Alternar mudo',
    source: 'pactl set-sink-mute toggle',
  },
  {
    id: 'volume-definir',
    module: 'audio',
    kind: 'acao',
    what: 'Definir o volume exato',
    source: 'pactl set-sink-volume N%',
  },
  {
    id: 'audio-trocar-saida',
    module: 'audio',
    kind: 'acao',
    what: 'Trocar a saída, movendo o que já toca',
    source: 'pactl set-default-sink + move-sink-input',
  },
  {
    id: 'audio-espectro',
    module: 'audio',
    kind: 'leitura',
    what: 'O espectro do que toca: a onda da pílula segue a música',
    source: 'parec no @DEFAULT_MONITOR@ + Goertzel em 5 faixas (island/espectro.ts)',
  },

  // ——— Mídia —————————————————————————————————————————
  {
    id: 'midia-tocando',
    module: 'midia',
    kind: 'leitura',
    what: 'Faixa, artista e capa',
    source: 'MPRIS (D-Bus)',
  },
  {
    id: 'midia-estado',
    module: 'midia',
    kind: 'leitura',
    what: 'Tocando, pausado ou parado',
    source: 'MPRIS PlaybackStatus',
  },
  {
    id: 'midia-progresso',
    module: 'midia',
    kind: 'leitura',
    what: 'Posição e duração',
    source: 'MPRIS Position/Metadata',
  },
  {
    id: 'midia-player',
    module: 'midia',
    kind: 'leitura',
    what: 'Qual player está ativo',
    source: 'MPRIS ListNames',
  },
  {
    id: 'midia-modos',
    module: 'midia',
    kind: 'leitura',
    what: 'Embaralhar e repetir, como o player diz',
    source: 'propriedades Shuffle e LoopStatus do MPRIS',
  },
  {
    id: 'midia-embaralhar',
    module: 'midia',
    kind: 'acao',
    what: 'Ligar ou desligar o embaralhar',
    source: 'propriedade Shuffle do MPRIS',
  },
  {
    id: 'midia-repetir',
    module: 'midia',
    kind: 'acao',
    what: 'Alternar o repetir (nenhum → lista → faixa)',
    source: 'propriedade LoopStatus do MPRIS',
  },
  {
    id: 'midia-buscar',
    module: 'midia',
    kind: 'acao',
    what: 'Ir para um instante da faixa',
    source: 'SetPosition do MPRIS, com o id da faixa',
  },
  {
    id: 'midia-copiar-link',
    module: 'midia',
    kind: 'acao',
    what: 'Copiar o link da faixa (xesam:url) para a área de transferência',
    source: 'Metadata do MPRIS + Klipper',
  },
  {
    id: 'midia-alternar',
    module: 'midia',
    kind: 'acao',
    what: 'Tocar ou pausar',
    source: 'MPRIS PlayPause',
  },
  {
    id: 'midia-proxima',
    module: 'midia',
    kind: 'acao',
    what: 'Próxima faixa',
    source: 'MPRIS Next',
  },
  {
    id: 'midia-anterior',
    module: 'midia',
    kind: 'acao',
    what: 'Faixa anterior',
    source: 'MPRIS Previous',
  },
  {
    id: 'midia-abrir',
    module: 'midia',
    kind: 'acao',
    what: 'Trazer o player para a frente',
    source: 'MPRIS Raise',
  },

  // ——— Rede ——————————————————————————————————————————
  {
    id: 'rede-conexao',
    module: 'rede',
    kind: 'leitura',
    what: 'Conexão ativa e tipo',
    source: 'nmcli device',
  },
  {
    id: 'wifi-sinal',
    module: 'rede',
    kind: 'leitura',
    what: 'Força do sinal Wi-Fi',
    source: 'nmcli device wifi',
  },
  {
    id: 'rede-ip',
    module: 'rede',
    kind: 'leitura',
    what: 'Endereço IP local',
    source: 'hostname -I',
  },
  {
    id: 'rede-baixando',
    module: 'rede',
    kind: 'leitura',
    what: 'Vazão de download',
    source: '/proc/net/dev (duas amostras)',
  },
  {
    id: 'rede-enviando',
    module: 'rede',
    kind: 'leitura',
    what: 'Vazão de upload',
    source: '/proc/net/dev (duas amostras)',
  },
  {
    id: 'wifi-alternar',
    module: 'rede',
    kind: 'acao',
    what: 'Ligar ou desligar o Wi-Fi',
    source: 'nmcli radio wifi',
  },

  // ——— Bluetooth —————————————————————————————————————
  {
    id: 'bluetooth',
    module: 'bluetooth',
    kind: 'leitura',
    what: 'Adaptador ligado ou não',
    source: 'bluetoothctl show',
  },
  {
    id: 'bluetooth-conectados',
    module: 'bluetooth',
    kind: 'leitura',
    what: 'Dispositivos conectados',
    source: 'bluetoothctl devices Connected',
  },
  {
    id: 'bluetooth-alternar',
    module: 'bluetooth',
    kind: 'acao',
    what: 'Ligar ou desligar o Bluetooth',
    source: 'bluetoothctl power',
  },
  {
    id: 'bluetooth-bateria',
    module: 'bluetooth',
    kind: 'leitura',
    what: 'Bateria dos dispositivos Bluetooth que a informam (fones, mouse)',
    source: 'org.bluez.Battery1 no bus de sistema',
  },

  // ——— Área de trabalho ————————————————————————————————
  {
    id: 'kde-desktop',
    module: 'desktop',
    kind: 'leitura',
    what: 'Área de trabalho virtual atual',
    source: 'qdbus6 org.kde.KWin currentDesktop',
  },
  {
    id: 'kde-desktop-total',
    module: 'desktop',
    kind: 'leitura',
    what: 'Quantas áreas de trabalho existem',
    source: 'qdbus6 VirtualDesktopManager count',
  },
  {
    id: 'cafeina',
    module: 'desktop',
    kind: 'leitura',
    what: 'Quem está mantendo a tela acordada',
    source: 'ListInhibitions do PolicyAgent do KDE',
  },
  {
    id: 'cafeina-alternar',
    module: 'desktop',
    kind: 'acao',
    what: 'Manter a tela acordada (cafeína) ou soltar',
    source: 'Inhibit/UnInhibit de org.freedesktop.ScreenSaver, por conexão viva do dbus-next',
  },
  {
    id: 'kde-desktop-proxima',
    module: 'desktop',
    kind: 'acao',
    what: 'Ir para a próxima área de trabalho',
    source: 'qdbus6 nextDesktop',
  },
  {
    id: 'kde-desktop-anterior',
    module: 'desktop',
    kind: 'acao',
    what: 'Voltar uma área de trabalho',
    source: 'qdbus6 previousDesktop',
  },
  {
    id: 'kde-mostrar-desktop',
    module: 'desktop',
    kind: 'acao',
    what: 'Mostrar a área de trabalho',
    source: 'qdbus6 showDesktop',
  },
  {
    id: 'kde-bloquear',
    module: 'desktop',
    kind: 'acao',
    what: 'Bloquear a tela',
    source: 'qdbus6 org.freedesktop.ScreenSaver Lock',
  },
  {
    id: 'kde-captura',
    module: 'desktop',
    kind: 'acao',
    what: 'Capturar a tela',
    source: 'spectacle -b -c',
  },
  {
    id: 'kde-notificar',
    module: 'desktop',
    kind: 'acao',
    what: 'Enviar aviso na bandeja',
    source: 'notify-send',
  },
  {
    id: 'cor-capturar',
    module: 'desktop',
    kind: 'acao',
    what: 'Conta-gotas: pegar a cor de um ponto da tela e copiar o #hex',
    source: 'org.kde.kwin.ColorPicker.pick (D-Bus) + Klipper',
  },

  // ——— Relógio e clima ————————————————————————————————
  {
    id: 'relogio-hora',
    module: 'tempo',
    kind: 'leitura',
    what: 'Hora atual',
    source: 'relógio do sistema',
  },
  {
    id: 'relogio-data',
    module: 'tempo',
    kind: 'leitura',
    what: 'Data por extenso',
    source: 'relógio do sistema',
  },
  {
    id: 'clima-temp',
    module: 'tempo',
    kind: 'leitura',
    what: 'Temperatura lá fora',
    source: 'Open-Meteo (serviço do app)',
  },
  {
    id: 'clima-condicao',
    module: 'tempo',
    kind: 'leitura',
    what: 'Condição do tempo',
    source: 'Open-Meteo (serviço do app)',
  },
  {
    id: 'relogio-mundo',
    module: 'tempo',
    kind: 'leitura',
    what: 'Relógios de outros fusos, escolhidos em Configurações',
    source: 'Intl.DateTimeFormat com island.clocks',
  },
  {
    id: 'timer-restante',
    module: 'tempo',
    kind: 'leitura',
    what: 'Quanto falta no temporizador',
    source: 'island/timer.ts (memória do main)',
  },
  {
    id: 'timer-iniciar',
    module: 'tempo',
    kind: 'acao',
    what: 'Começar um temporizador (minutos e rótulo)',
    source: 'island/timer.ts; anuncia e avisa pelo notify-send ao acabar',
  },
  {
    id: 'timer-cronometro',
    module: 'tempo',
    kind: 'acao',
    what: 'Começar um cronômetro (conta para cima)',
    source: 'island/timer.ts',
  },
  {
    id: 'timer-parar',
    module: 'tempo',
    kind: 'acao',
    what: 'Parar o temporizador',
    source: 'island/timer.ts',
  },

  // ——— Área de transferência e nota ——————————————————
  {
    id: 'clip-recentes',
    module: 'clips',
    kind: 'leitura',
    what: 'Histórico do que foi copiado (só em memória)',
    source: 'Klipper pelo D-Bus (org.kde.klipper), a cada segundo; Electron fora do KDE',
  },
  {
    id: 'clip-copiar',
    module: 'clips',
    kind: 'acao',
    what: 'Pôr um item do histórico de volta na área de transferência',
    source: 'setClipboardContents do Klipper; clipboard.writeText fora do KDE',
  },
  {
    id: 'clip-fixar',
    module: 'clips',
    kind: 'acao',
    what: 'Fixar um item para ele não cair do histórico',
    source: 'island/clipboard.ts',
  },
  {
    id: 'clip-remover',
    module: 'clips',
    kind: 'acao',
    what: 'Tirar um item do histórico',
    source: 'island/clipboard.ts',
  },
  {
    id: 'clip-limpar',
    module: 'clips',
    kind: 'acao',
    what: 'Limpar o histórico (os fixados ficam)',
    source: 'island/clipboard.ts',
  },
  {
    id: 'nota-salvar',
    module: 'clips',
    kind: 'acao',
    what: 'Guardar a nota rápida',
    source: 'island.note em settings.json, escrito pelo main',
  },

  // ——— Notificações do sistema ————————————————————————
  {
    id: 'avisos-recentes',
    module: 'avisos',
    kind: 'leitura',
    what: 'As últimas notificações que os aplicativos mandaram',
    source: 'dbus-monitor em org.freedesktop.Notifications.Notify',
  },
  {
    id: 'avisos-vigia',
    module: 'avisos',
    kind: 'leitura',
    what: 'Se o vigia de notificações está ouvindo',
    source: 'island/watch.ts',
  },
  {
    id: 'silencio',
    module: 'avisos',
    kind: 'leitura',
    what: 'Se o "não perturbe" do KDE está ligado',
    source: 'propriedade Inhibited de org.freedesktop.Notifications',
  },
  {
    id: 'silencio-alternar',
    module: 'avisos',
    kind: 'acao',
    what: 'Ligar ou desligar o "não perturbe"',
    source: 'Inhibit/UnInhibit de org.freedesktop.Notifications, por conexão viva do dbus-next',
  },
  {
    id: 'avisos-abrir-app',
    module: 'avisos',
    kind: 'acao',
    what: 'Abrir o aplicativo que mandou a notificação',
    source: 'dica desktop-entry do Notify + gio launch',
  },
  {
    id: 'avisos-remover',
    module: 'avisos',
    kind: 'acao',
    what: 'Dispensar uma notificação da lista da ilha',
    source: 'island/watch.ts (memória do main)',
  },
  {
    id: 'avisos-limpar',
    module: 'avisos',
    kind: 'acao',
    what: 'Limpar a lista de notificações da ilha',
    source: 'island/watch.ts (memória do main)',
  },

  // ——— O próprio Halo ————————————————————————————————
  {
    id: 'halo-agentes',
    module: 'halo',
    kind: 'leitura',
    what: 'Agentes do Claude abertos e o que fazem',
    source: 'serviço de agentes do app',
  },
  {
    id: 'halo-containers',
    module: 'halo',
    kind: 'leitura',
    what: 'Containers do Docker ativos',
    source: 'docker ps (serviço do app)',
  },
  {
    id: 'halo-projetos',
    module: 'halo',
    kind: 'leitura',
    what: 'Projetos git com alterações',
    source: 'git (serviço do app)',
  },
  {
    id: 'halo-tela',
    module: 'halo',
    kind: 'acao',
    what: 'Trazer a janela do Halo à vista',
    source: 'IPC do app',
  },
  {
    id: 'halo-na-ilha',
    module: 'halo',
    kind: 'leitura',
    what: 'O app está recolhido na ilha?',
    source: 'estado do main (island/halo.ts)',
  },
  {
    id: 'halo-recolher',
    module: 'halo',
    kind: 'acao',
    what: 'Recolher a janela do Halo para a pílula (Meta+Space)',
    source: 'BrowserWindow.hide() + voo da camada do fantasma',
  },
  {
    id: 'halo-trazer',
    module: 'halo',
    kind: 'acao',
    what: 'Trazer o Halo de volta da pílula, ao lugar de onde saiu',
    source: 'BrowserWindow.showInactive() + camada do papel de parede',
  },

  // ——— Aplicativos e arquivos ————————————————————————
  {
    id: 'apps-buscar',
    module: 'apps',
    kind: 'leitura',
    what: 'Buscar entre os aplicativos instalados',
    source: 'arquivos .desktop (serviço do app)',
  },
  {
    id: 'apps-abrir',
    module: 'apps',
    kind: 'acao',
    what: 'Abrir um aplicativo',
    source: 'gio launch',
  },
  {
    id: 'abrir-caminho',
    module: 'apps',
    kind: 'acao',
    what: 'Abrir pasta, arquivo ou endereço',
    source: 'gio open',
  },
  {
    id: 'downloads-andamento',
    module: 'apps',
    kind: 'leitura',
    what: 'Downloads em andamento (arquivos parciais do navegador)',
    source: '~/Downloads: *.part, *.crdownload, *.partial',
  },
  {
    id: 'capturas-recentes',
    module: 'apps',
    kind: 'leitura',
    what: 'Capturas de tela na pasta do Spectacle; a nova vai para a gaveta',
    source: 'spectaclerc + pasta de imagens do XDG',
  },
  {
    id: 'downloads-recentes',
    module: 'apps',
    kind: 'leitura',
    what: 'Últimos arquivos baixados',
    source: 'sistema de arquivos (~/Downloads)',
  },
  {
    id: 'texto-da-imagem',
    module: 'apps',
    kind: 'acao',
    what: 'Ler o texto de uma imagem (OCR) e copiar',
    source: 'tesseract + Klipper',
  },
  {
    id: 'texto-da-tela',
    module: 'apps',
    kind: 'acao',
    what: 'Ler o texto de um pedaço da tela (região) e copiar',
    source: 'spectacle -r em arquivo temporário do app + tesseract',
  },

  // ——— A gaveta de arquivos ————————————————————————————
  {
    id: 'gaveta-arquivos',
    module: 'gaveta',
    kind: 'leitura',
    what: 'O que está guardado na gaveta',
    source: 'island.shelf em settings.json (escrito pelo main)',
  },
  {
    id: 'gaveta-guardar',
    module: 'gaveta',
    kind: 'acao',
    what: 'Guardar um arquivo ou endereço na gaveta',
    source: 'referência ao caminho — nunca cópia',
  },
  {
    id: 'gaveta-guardar-texto',
    module: 'gaveta',
    kind: 'acao',
    what: 'Guardar um trecho de texto solto na pílula',
    source: 'arquivo novo em ~/.local/share/halo-spatial-os/gaveta/',
  },
  {
    id: 'gaveta-remover',
    module: 'gaveta',
    kind: 'acao',
    what: 'Tirar um arquivo da gaveta',
    source: 'island.shelf em settings.json',
  },
  {
    id: 'gaveta-limpar',
    module: 'gaveta',
    kind: 'acao',
    what: 'Esvaziar a gaveta',
    source: 'island.shelf em settings.json',
  },
  {
    id: 'gaveta-abrir',
    module: 'gaveta',
    kind: 'acao',
    what: 'Abrir um arquivo guardado',
    source: 'gio open',
  },
  {
    id: 'gaveta-enviar',
    module: 'gaveta',
    kind: 'acao',
    what: 'Enviar um arquivo guardado ao Seafile',
    source: 'serviço do Seafile do app',
  },

  // ——— Janelas (scripting do KWin) ——————————————————————
  {
    id: 'janelas-abertas',
    module: 'janelas',
    kind: 'leitura',
    what: 'As janelas abertas no computador',
    source: 'script no KWin via D-Bus (workspace.windowList)',
  },
  {
    id: 'janelas-guardadas',
    module: 'janelas',
    kind: 'leitura',
    what: 'Janelas guardadas na gaveta',
    source: 'memória do main',
  },
  {
    id: 'janela-guardar',
    module: 'janelas',
    kind: 'acao',
    what: 'Guardar uma janela (minimiza e lembra)',
    source: 'script no KWin: minimized = true',
  },
  {
    id: 'janela-restaurar',
    module: 'janelas',
    kind: 'acao',
    what: 'Devolver uma janela guardada',
    source: 'script no KWin: minimized = false + activeWindow',
  },
  {
    id: 'janela-focar',
    module: 'janelas',
    kind: 'acao',
    what: 'Trazer uma janela para a frente',
    source: 'script no KWin: activeWindow',
  },
  {
    id: 'janela-encaixar',
    module: 'janelas',
    kind: 'acao',
    what: 'Encaixar uma janela: metade esquerda, direita ou maximizada',
    source: 'scripting do KWin (frameGeometry, clientArea)',
  },
  {
    id: 'janelas-vigia',
    module: 'janelas',
    kind: 'leitura',
    what: 'Se o vigia do KWin está de pé (tela cheia esconde a ilha; atalho opcional)',
    source: 'script persistente halo-ilha-vigia no KWin',
  },

  // ——— O celular (KDE Connect) ——————————————————————————
  {
    id: 'celular-dispositivo',
    module: 'celular',
    kind: 'leitura',
    what: 'O celular pareado e se está ao alcance',
    source: 'org.kde.kdeconnect.device pelo D-Bus',
  },
  {
    id: 'celular-bateria',
    module: 'celular',
    kind: 'leitura',
    what: 'Bateria do celular e se está carregando',
    source: 'org.kde.kdeconnect.device.battery',
  },
  {
    id: 'celular-tocar',
    module: 'celular',
    kind: 'acao',
    what: 'Fazer o celular tocar para achá-lo',
    source: 'org.kde.kdeconnect.device.findmyphone.ring',
  },
  {
    id: 'celular-ping',
    module: 'celular',
    kind: 'acao',
    what: 'Mandar um ping ao celular',
    source: 'org.kde.kdeconnect.device.ping.sendPing',
  },
  {
    id: 'celular-enviar',
    module: 'celular',
    kind: 'acao',
    what: 'Enviar um arquivo da gaveta (ou um endereço) ao celular',
    source: 'org.kde.kdeconnect.device.share.shareUrl',
  },
  {
    id: 'celular-enviar-texto',
    module: 'celular',
    kind: 'acao',
    what: 'Enviar um trecho de texto ao celular',
    source: 'org.kde.kdeconnect.device.share.shareText',
  },

  // ——— Discos removíveis ————————————————————————————————
  {
    id: 'discos-removiveis',
    module: 'discos',
    kind: 'leitura',
    what: 'Pendrives e discos externos conectados; anuncia quando entram e saem',
    source: 'lsblk -J (rm, hotplug, usb)',
  },
  {
    id: 'discos-montados',
    module: 'discos',
    kind: 'leitura',
    what: 'Quais partições removíveis estão montadas, e onde',
    source: 'lsblk -J',
  },
  {
    id: 'discos-lista',
    module: 'discos',
    kind: 'leitura',
    what: 'A lista de volumes removíveis para o painel (rótulo, ponto, livre)',
    source: 'lsblk -J',
  },
  {
    id: 'disco-ejetar',
    module: 'discos',
    kind: 'acao',
    what: 'Ejetar com segurança: desmonta e desliga; a ilha diz "pode tirar"',
    source: 'udisksctl unmount + power-off',
  },
  {
    id: 'disco-montar',
    module: 'discos',
    kind: 'acao',
    what: 'Montar uma partição removível',
    source: 'udisksctl mount',
  },
  {
    id: 'disco-abrir',
    module: 'discos',
    kind: 'acao',
    what: 'Abrir um volume montado no gerenciador de arquivos',
    source: 'gio open',
  },

  // ——— Teclado ——————————————————————————————————————————
  {
    id: 'teclado-capslock',
    module: 'teclado',
    kind: 'leitura',
    what: 'Caps Lock ligado ou não',
    source: '/sys/class/leds/*::capslock/brightness',
  },
  {
    id: 'teclado-numlock',
    module: 'teclado',
    kind: 'leitura',
    what: 'Num Lock ligado ou não',
    source: '/sys/class/leds/*::numlock/brightness',
  },
  {
    id: 'teclado-vigia',
    module: 'teclado',
    kind: 'leitura',
    what: 'Se o HUD das travas está de pé (Caps Lock mostra na pílula)',
    source: 'island/teclado.ts (LEDs a cada 200ms)',
  },

  // ——— Foco ————————————————————————————————————————————
  {
    id: 'foco-hoje',
    module: 'foco',
    kind: 'leitura',
    what: 'Minutos de foco hoje (temporizadores que chegaram ao fim)',
    source: 'island.focus em settings.json (escrito pelo main)',
  },
  {
    id: 'foco-semana',
    module: 'foco',
    kind: 'leitura',
    what: 'Minutos por dia nos últimos 7 dias — o gráfico da home',
    source: 'island.focus em settings.json',
  },
  {
    id: 'foco-sequencia',
    module: 'foco',
    kind: 'leitura',
    what: 'Dias seguidos com pelo menos uma sessão',
    source: 'island.focus em settings.json',
  },
  {
    id: 'foco-limpar',
    module: 'foco',
    kind: 'acao',
    what: 'Apagar o histórico de foco',
    source: 'island.focus em settings.json',
  },

  // ——— A API local ———————————————————————————————————————
  {
    id: 'api-socket',
    module: 'api',
    kind: 'leitura',
    what: 'O socket Unix onde scripts publicam atividades e avisos',
    source: '$XDG_RUNTIME_DIR/halo-ilha.sock (0600), island/api.ts',
  },
  {
    id: 'api-atividades',
    module: 'api',
    kind: 'leitura',
    what: 'Atividades publicadas de fora (shell, hooks do Claude Code)',
    source: 'memória do main (island/api.ts)',
  },
  {
    id: 'api-atividade-limpar',
    module: 'api',
    kind: 'acao',
    what: 'Tirar uma atividade da lista',
    source: 'island/api.ts',
  },

  // ——— O Claude da ilha ————————————————————————————————
  {
    id: 'claude-estado',
    module: 'claude',
    kind: 'leitura',
    what: 'O agente da ilha: pensando, usando ferramenta, esperando permissão',
    source: 'serviço de agentes do app (CLI em stream-json)',
  },
  {
    id: 'claude-projeto',
    module: 'claude',
    kind: 'leitura',
    what: 'Onde o agente roda e com que modo de permissão',
    source: 'claude.projects e claude.mode nas configurações',
  },
  {
    id: 'claude-aprovacao',
    module: 'claude',
    kind: 'leitura',
    what: 'O pedido de permissão parado à espera da resposta',
    source: 'control_request can_use_tool do CLI (--permission-prompt-tool stdio)',
  },
  {
    id: 'claude-resposta',
    module: 'claude',
    kind: 'leitura',
    what: 'A última resposta do Claude da ilha',
    source: 'mensagens do agente',
  },
  {
    id: 'claude-perguntar',
    module: 'claude',
    kind: 'acao',
    what: 'Perguntar ao Claude, com o contexto da ilha (cópia, avisos, faixa, arquivo)',
    source: 'sendToAgent com --append-system-prompt e anexos (imagem vira imagem)',
  },
  {
    id: 'claude-aprovar',
    module: 'claude',
    kind: 'acao',
    what: 'Permitir ou negar a ferramenta que o Claude pediu',
    source: 'control_response pela entrada do CLI',
  },
  {
    id: 'claude-parar',
    module: 'claude',
    kind: 'acao',
    what: 'Encerrar a conversa (a próxima pergunta abre outra)',
    source: 'closeAgent',
  },
  {
    id: 'claude-projeto-definir',
    module: 'claude',
    kind: 'acao',
    what: 'Escolher em qual projeto fixado o próximo agente roda',
    source: 'island/claude.ts',
  },
]
